### ISSUE TITLE
オリジナルDiceの追加について

### ISSUE THREAD

**Issue by Sizuku2847** [Shunshun94/discord-bcdicebot#38]
やってて気づいた仕様なのかわからないものを一点。
起動したまま追加したいコマンドが書かれたテキストをフォルダに入れて
bcdice admin [パスワード] addDiceBot [ダイスボット名]
と打つと
ダイスボットを登録する際はダイスボットのファイルをアップロードする必要があります
って出ます。
なので一度アプリケーションを落とし、再起動させてコマンド打とうとしたら、すでに導入済みになってました。
正規の動作をしているか微妙だったのでご報告を。

（ほしい機能としては1-5の値でこの言葉を返す。のような風にできるとさらに楽だと思いました...。）

**Comment by Shunshun94** [comment]
（チャットで話したのでいるのか微妙ですが記録として返答）

手動でテキストをフォルダに入れるのではなく、   
`bcdice admin [パスワード] addDiceBot [ダイスボット名]` と打ちながらチャットの添付ファイルとしてファイルをアップロードするとダイスボットが追加されます。

ダイスボットを起動した時点ではフォルダに入っているファイルをオリジナルのダイスボットとして利用します。

このため、予定通りの挙動です。
