### ISSUE TITLE
bot の公開を検討する

### ISSUE THREAD

**Issue by Shunshun94** [Shunshun94/discord-bcdicebot#65]
どこまでいける？
デイコードさんはオープンにしているがどうやっている？同じやり方をまねできる？できない？

**Comment by Shunshun94** [comment]
https://dinosaur-fossil.hatenablog.com/
うーん、これなら比較的誰でも無料で導入できるし今更出す意味あるか？
これ、載せてもいい？って尋ねた方がよくね？

**Comment by blhsrwznrghfzpr** [comment]
ブログ主です。載せていただけるのは構わないです。

記事中にある、heroku用のProcfileのPullRequestを出してもいいでしょうか？

**Comment by Shunshun94** [comment]
なんと。ありがとうございます！

> 記事中にある、heroku用のProcfileのPullRequestを出してもいいでしょうか？
頂けると大変ありがたいです。ありがとうございます！
develop ブランチに対して PR を出していただければ確認後マージいたします。

**Comment by Shunshun94** [comment]
ダイスボット表がにゃーんする問題について解決策を追記したら閉じて 2.2.0 として公開する。
英語で命名しろ、と言いたいけれど「そんな御無体な……」ってなる気がする。

**Comment by Shunshun94** [comment]
別に切った。今後の課題とするので閉じ
