### ISSUE TITLE
オリジナルDice表の前方一致によって似たり寄ったりを認識しない。

### ISSUE THREAD

**Issue by Sizuku2847** [Shunshun94/discord-bcdicebot#91]
例：SNSとSNSMという表を用意した場合、SNSMを実行した際SNSの表が振られてしまいます。
![image](https://user-images.githubusercontent.com/55372874/113098350-56ab8200-9233-11eb-87fc-0c7746507838.png)

**Comment by Shunshun94** [comment]
どの表なのかの判定ロジック：ユーザの入力に対し、ダイスボットの名前が一致するかを適当な順番で比較する
`cat`, `neko`, `nekonbu` という表がある場合に
`neko` を入れると

1. `neko` の先頭は `cat` と合致しないのでハズれ
2. `neko` の先頭は `neko` と合致するのでアタり→ `neko` を返却する

が、 `nekonbu` を入れると

1. `nekonbu` の先頭は `cat` と合致しないのでハズれ
2. `nekonbu` の先頭は `neko` と合致するのでアタり→ `neko` を返却する：期待と異なる結果

単純には表の評価順を長さ順にするのが良さそう。
`nekonbu` `neko` `cat` の順番で評価させる
