### ISSUE TITLE
start.sh: 改行コードが原因でUNIX系システムから実行できない

### ISSUE THREAD

**Issue by ochaochaocha3** [Shunshun94/discord-bcdicebot#92]
UNIX系システムのbash等で、起動用シェルスクリプトstart.shを実行しようとすると、以下のエラーが表示されます。

```
-bash: ./start.sh: /bin/sh^M: 誤ったインタプリタです: No such file or directory
```

原因は、https://github.com/Shunshun94/discord-bcdicebot/commit/9f86d633bd37e7337a218c9fc98b678e9b91cca9#diff-65a5db1ae8f8e01ebdbbfafcf4e24618ad7cffe036bba92dce1390383e5c73e5 で改行コードがCR+LFに変更されたことのようです。改行コードをLFに戻せば正常に動作すると思います。

**Comment by Shunshun94** [comment]
ありがとうございます。修正し、修正版を公開しました。

**Comment by ochaochaocha3** [comment]
ご対応ありがとうございます。無事実行できました！
