### ISSUE TITLE
テスト失敗によりJARを生成できない

### ISSUE THREAD

**Issue by ochaochaocha3** [Shunshun94/discord-bcdicebot#96]
現在、テストが失敗するため、`mvn install` によってJARを生成できなくなっています。`mvn install -DskipTests=true` でテストを実行しないように設定することで進みますが、これは分かりにくい操作ですので、修正を希望します。

原因は以下の2つです。

* `testDiceBots/ダブルクロス-トライブリード` が存在しません。
    * `java.io.IOException: ダイスボット [ダブルクロス-トライブリード] が見つかりませんでした` が発生します。
    * リポジトリへの追加漏れでしょうか。このファイルを追加するか、`IOException` を `catch` すると発生しなくなります。
* Windows以外の環境において、環境変数の差し替えが失敗します。
    * 修正案を #95 として作成しました。

**Comment by Shunshun94** [comment]
ありがとうございます！Develop に修正を反映しました。
各種文章への修正を行った後 master に入れます。

**Comment by ochaochaocha3** [comment]
ご対応ありがとうございます！
